#+TITLE: Bootstrap
#+AUTHOR: Levi Crews
#+EMAIL: levigcrews@gmail.com

* TODO add file-local-var to automatically tangle this doc
* TODO add description of this file
* TODO replace =find= and =grep= in =pdfsearch= command to speed it up
* bootstrap script
Adapted from https://github.com/rkalis/dotfiles and associated blog posts.

#+begin_src shell :tangle "bootstrap.sh"
#! /usr/bin/env sh

DIR=$(dirname "$0")
cd "$DIR"

source coloredecho.sh

info "Prompting for sudo password..."
if sudo -v; then
    # Keep-alive: update existing `sudo` time stamp until `setup.sh` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    success "Sudo credentials updated."
else
    error "Failed to obtain sudo credentials."
fi

COMMENT=\#*

sudo -v
add-apt-repository ppa:kelleyk/emacs
add-apt-repository ppa:inkscape.dev/stable
apt update

# install Rust & Cargo (its package manager)
curl https://sh.rustup.rs -sSf | sh

find * -name "*.list" | while read fn; do
    cmd="${fn%.*}" # Bash string operator
    set -- $cmd
    info "Installing $1 packages..."
    while read package; do
        if [[ $package == $COMMENT ]]; then continue; fi
        if [[ $cmd == code ]]; then
            substep_info "Installing VSCode extension $package..."
            $cmd --install-extension $package
        elif [[ $cmd == npm ]]; then
            substep_info "Installing Node.js package $package..."
            $cmd install -g $package
        else
            substep_info "Installing $package..."
            $cmd install $package
        fi
    done < "$fn"
    success "Finished installing $1 packages."
done

chmod +x /usr/local/bin/pdfsearch
#+end_src
* colored progress messages
Taken again from https://github.com/rkalis/dotfiles and associated blog posts. Called in ~bootstrap.sh~ to give the user easy-to-read progress updates as the installation proceeds.
#+begin_src shell :tangle "coloredecho.sh"
#! /usr/bin/env sh

# Took these printing functions from https://github.com/Sajjadhosn/dotfiles
coloredEcho() {
    local exp="$1";
    local color="$2";
    local arrow="$3";
    if ! [[ $color =~ '^[0-9]$' ]] ; then
       case $(echo $color | tr '[:upper:]' '[:lower:]') in
        black) color=0 ;;
        red) color=1 ;;
        green) color=2 ;;
        yellow) color=3 ;;
        blue) color=4 ;;
        magenta) color=5 ;;
        cyan) color=6 ;;
        white|*) color=7 ;; # white or invalid color
       esac
    fi
    tput bold;
    tput setaf "$color";
    echo "$arrow $exp";
    tput sgr0;
}

info() {
    coloredEcho "$1" blue "========>"
}

success() {
    coloredEcho "$1" green "========>"
}

error() {
    coloredEcho "$1" red "========>"
}

substep_info() {
    coloredEcho "$1" magenta "===="
}

substep_success() {
    coloredEcho "$1" cyan "===="
}

substep_error() {
    coloredEcho "$1" red "===="
}
#+end_src
* apt.list
** list
#+begin_src :tangle "apt.list"
bat
bmon
cookiecutter
curl
diatheke
emacs26
fd-find
font-manager
fonts-powerline
fzf
gdebi
gdebi-core
gh
git
golang-go
graphviz
htop
httpie
hugo
inkscape
jq
manpages-dev
mdp
miller
mmv
nodejs
npm
pdftk
pympress
python3-pip
python3-pyqt5
qalc
qpdfview
r-base
ripgrep
rofi
rstudio
samba
scrot
silversearcher-ag
shellcheck
sqlite3
surfraw
sword-text-kjv
sxhkd
texlive
latexmk
viewnior
visidata
w3m
wordnet
xclip
yadm
youtube-dl
zathura
#+end_src
** notes

A number of the tools I install are modern/faster/saner alternatives to common Unix commands. A collection of such tools is maintained in the [[https://github.com/ibraheemdev/modern-unix][modern-unix]] repo on GitHub.

*** [[https://github.com/sharkdp/bat][bat]]: =cat= clone with syntax highlighting and Git integration
- aliased for =cat=
*** [[https://github.com/tgraf/bmon][bmon]]: bandwidth monitor
- called by ~rofi~
*** [[https://github.com/cookiecutter/cookiecutter][cookiecutter]]: A command-line utility that creates projects from cookiecutters (project templates)
*** diatheke: command line Bible reader
*** [[https://github.com/junegunn/fzf][fzf]]: a command line fuzzy finder
*** [[https://github.com/cli/cli][gh]]: GitHub CLI
- supercedes HTTPS and SSH interactions with GitHub
*** [[https://httpie.io/][httpie]]: a user-friendly command-line HTTP client for the API era
- comes with JSON support, syntax highlighting, persistent sessions, wget-like downloads, plugins, ...
- can replace =curl= and =wget=
*** [[https://github.com/inkscape/inkscape][inkscape]]: free and open source vector drawing
- Castel: [[https://castel.dev/post/lecture-notes-2/][How I draw figures for my math notes using Inkscape]]
*** [[https://stedolan.github.io/jq/tutorial/][jq]]: a lightweight and flexible command-line JSON processor
*** [[https://github.com/visit1985/mdp][mdp]]: command-line based Markdown presentation tool
*** [[https://github.com/johnkerl/miller][miller]]: like =awk=, =sed=, =cut=, =join=, and =sort= for name-indexed data such as CSV, TSV, and tabular JSON
*** [[https://github.com/itchyny/mmv][mmv]]: rename multiple files using your default editor
*** pdftk: command line tool to merge and split PDFs
- used to compile class slides into one PDF for entry in BibTeX database
- synatx :: ~pdftk <files> cat output <newfile>~
*** qalc: powerful and easy to use command line calculator
- called by ~rofi~ launcher
*** pdf viewers: qpdfview & zathura
*** [[https://github.com/BurntSushi/ripgrep][ripgrep]]: =grep=, but better
*** rofi
- explained in detail elsewhere
*** [[https://github.com/dreamer/scrot][scrot]]: command-line screenshot utility
- called by ~rofi~
*** [[https://github.com/ggreer/the_silver_searcher][silversearcher-ag]]: A code-searching tool similar to ack, but faster
*** [[https://gitlab.com/surfraw/Surfraw][surfraw]]: CLI to popular web search engines
*** sxhkd
- hotkey manager used to specify ~rofi~ hotkeys
- explained in detail elsewhere
*** [[https://www.visidata.org/][visidata]]: interactive multitool for tabular data
*** [[https://github.com/ytdl-org/youtube-dl/][youtube-dl]]
- download YouTube videos
** dependencies for =diff-pdf=
#+begin_src
automake
g++
libpoppler-glib-dev
libwxgtk3.0-dev
poppler-utils
#+end_src
* snap.list
** list
#+begin_src :tangle "snap.list"
--classic code
vlc
jabref
slack --classic
discord
harsh
bibletime
#+end_src
** notes
*** [[https://github.com/wakatara/harsh][harsh]]: A minimalist command line tool for tracking habits
- use Org mode instead, but I like the plots this makes better than Org's
*** [[https://github.com/bibletime/bibletime][bibletime]]: A powerful cross platform Bible study tool
* pip.list
** list
#+begin_src :tangle "pip.list"
bokeh
dask
docutils
econtools
eg
gme
grip
icdiff
minet
pipenv
pyomo
pyreadr
tldr
tqdm
quantecon
#+end_src
** notes
*** [[https://github.com/bokeh/bokeh][bokeh]]: interactive visualization library for modern web browsers
It provides elegant, concise construction of versatile graphics, and affords high-performance interactivity over large or streaming datasets. Bokeh can help anyone who would like to quickly and easily make interactive plots, dashboards, and data applications.
*** [[https://dask.org/][dask]]: scaling and parallelizing Pandas
*** [[https://pypi.org/project/docutils/][docutils]]: convert reStructuredText to HTML and LaTeX
*** [[http://www.danielmsullivan.com/econtools/][econtools]]: package with tools for econometrics and data munging
*** [[https://github.com/srsudar/eg][eg]]: useful examples at the command line
*** [[https://www.usitc.gov/data/gravity/gme.htm][gme]]: Python module for USITC Gravity Modeling Environment
*** [[https://github.com/joeyespo/grip][grip]]: Preview GitHub READMEs locally
*** [[https://github.com/jeffkaufman/icdiff][icdiff]]: improved colored diff
*** [[https://github.com/medialab/minet][minet]]: webmining command line tool
- can be used to collect and extract data from a large variety of web sources such as raw webpages, Facebook, YouTube, Twitter, etc.
*** [[https://github.com/pypa/pipenv][pipenv]]: automatically creates/manages a virtualenv for projects
*** [[http://www.pyomo.org/about][pyomo]]: modeling language with a diverse set of optimization capabilities
*** [[https://github.com/ofajardo/pyreadr][pyreadr]]: Python package to read/write R data files
*** [[https://github.com/tldr-pages/tldr][tldr]]: Community-sourced command-line cheatsheets
*** [[https://github.com/tqdm/tqdm][tqdm]]: a fast, extensible progress bar for Python and CLI
* cargo.list
** list
#+begin_src :tangle "cargo.list"
broot
du-dust
exa
sd
#+end_src
** notes
*** [[https://github.com/Canop/broot][broot]]: a new way to see and navigate directory trees
*** [[https://github.com/bootandy/dust][dust]]: a more intuitive version of =du= (disk usage) in rust
*** [[https://github.com/ogham/exa][exa]]: a modern replacement for =ls=
*** [[https://github.com/chmln/sd][sd]]: intuitive find & replace CLI (=sed= alternative)
* code.list
#+begin_src :tangle "code.list"
aaron-bond.better-comments
albert.tabout
arcticicestudio.nord-visual-studio-code
AffenWiesel.matlab-formatter
akamud.vscode-theme-onedark
alefragnani.numbered-bookmarks
alefragnani.project-manager
axetroy.vscode-changelog-generator
bierner.emojisense
bierner.markdown-checkbox
bungcip.better-toml
CoenraadS.bracket-pair-colorizer-2
DavidAnson.vscode-markdownlint
eamodio.gitlens
ericadamski.carbon-now-sh
formulahendry.code-runner
geddski.macros
Gimly81.matlab
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
Ikuyadeu.r
imjacobclark.vscode-lisp-formatter
James-Yu.latex-workshop
julialang.language-julia
KevinRose.vsc-python-indent
kylebarron.stata-enhanced
mikestead.dotenv
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
mxschmitt.postscript
oijaz.unicode-latex
patbenatar.advanced-new-file
PKief.material-icon-theme
quicktype.quicktype
RandomFractalsInc.geo-data-viewer
redhat.vscode-yaml
shd101wyy.markdown-preview-enhanced
sidneys1.gitconfig
sleistner.vscode-fileutils
tecosaur.latex-utilities
Tyriar.vscode-terminal-here
VisualStudioExptTeam.vscodeintellicode
vmsynkov.colonize
vscode-icons-team.vscode-icons
vscode-org-mode.org-mode
vsls-contrib.codetour
vsls-contrib.gistfs
wmaurer.change-case
wmaurer.vscode-jumpy
wwm.better-align
Yeaoh.stataRun
yzane.markdown-pdf
yzhang.markdown-all-in-one
#+end_src
* npm.list
** list
#+begin_src :tangle "npm.list"
carbon-now-cli
how-2
tldr
#+end_src
** notes
*** [[https://github.com/carbon-app/carbon][carbon]] and [[https://github.com/mixn/carbon-now-cli][carbon-now-cli]]: Create and share beautiful images of your source code
*** [[https://github.com/santinic/how2][how2]]: Stackoverflow from the terminal
*** [[https://github.com/tldr-pages/tldr][tldr]]: Collaborative cheatsheets for console commands
* custom bash scripts
** ~pdfsearch~: search all PDFs in current directory for string
[[https://stackoverflow.com/a/4643518/11952647][This Stackoverflow answer]] suggests the =find ... -exec sh -c ...=
framework that comprises the body of this short script. [[https://stackoverflow.com/a/4643518/11952647][This answer]]
taught me how to pass the search query to the =-exec= command.
The =-q= flag for =pdftotext= just silences error messages.
The =-m 1= flag for =grep= limits results to one per file.

#+begin_src shell :tangle "/usr/local/bin"
#! /usr/bin/env sh

tosearch=$1
find . -name '*.pdf' -exec sh -c 'pdftotext "{}" -q - | grep -m 1 --with-filename --label="{}" --color "$1"' sh "$tosearch" \;
#+end_src
** [[https://github.com/cheat/cheat][cheat]]: create and view custom interactive cheatsheets on the command line
- Cheatsheets are stored on "cheatpaths", which are directories that contain cheatsheets. Cheatpaths are specified in a YAML config file.
- Can store personal cheatsheets *and* community cheatsheets
- compare [[https://github.com/srsudar/eg][eg]] (in ~pip.list~) and [[https://github.com/tldr-pages/tldr][tldr]] (in ~npm.list~), which *only* provide stock examples
- compare [[https://github.com/gnebbia/kb][kb]], which aims to be a full CLI knowledge base
