#+TITLE: config
#+DESCRIPTION: My private Doom Emacs configuration

#+BEGIN_SRC elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC

* Getting help
You can always read the [[https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org][documentation]] or the [[https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org][FAQ]], but with Emacs' built-in help system, documentation is actually just a keystroke away:
- for functions :: 'C-h f'
- for variables :: 'C-h v'
- for a keybind :: 'C-h k'
- to search available keybinds :: 'C-h b b'
* Compiled lists to work your way through
** [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]]: A community driven list of useful Emacs packages, utilities, libraries, and tutorials
Many of the packages listed in Awesome Emacs are either (i) already included here or (ii) are rendered redundant by this configuration. That said, there's still plenty to be discovered by looking through the list, especially if your needs differ from mine. If you're interested in a pre-built Emacs distribution but you don't like this one, give a careful look to the *Starter Kit* heading of the list.
** [[https://github.com/thinkhuman/writingwithemacs][Writing with Emacs]]: Tips, examples, and resources for writing with Emacs
Most writers are not hackers, too, but many have turned to Emacs nonetheless as their writing tool of choice.
* How to configure Doom Emacs
/Remember/: you do not need to run =doom sync= after modifying this file! It is sufficient to reload Doom with =M-x doom/reload= or =C-h r r=. In practice, though, I've found that =doom sync= is the only fool-proof way for your changes to take effect.

Here are some additional functions/macros that could help you configure Doom:
- =load!= for loading external ~*.el~ files relative to this one
- =use-package!= for configuring packages
- =after!= for running code after a package has loaded
- =add-load-path!= for adding directories to the =load-path=, relative to
  this file. Emacs searches the =load-path= when you load packages with
  =require= or =use-package=.
- =map!= for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press =C-c c k= (evil users must press just =K=).
This will open documentation for it, including demos of how they are used.

You can also try =gd= (or =C-c c d=) to jump to their definition and see how
they are implemented.

* User info
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+BEGIN_SRC elisp
(setq user-full-name "Levi Crews"
      user-mail-address "levigcrews@gmail.com")
#+END_SRC

* Don't tangle this config on save
#+begin_src elisp
(remove-hook 'org-mode-hook #'+literate-enable-recompile-h)
#+end_src
* Syncing
Following this [[https://www.nicklanasa.com/posts/emacs-syncing-dropbox-beorg][post]] from Nick Lanasa, the following block ensures that your local Emacs and Beorg always stay in sync via Dropbox.
- ~auto-save-mode~ is used to save files in the background when you don't save them explicitly. This propagates changes from local Emacs to Beorg.
- ~auto-revert-mode~ is used to propagate changes from Beorg automagically back to your local Emacs.
#+begin_src elisp
(setq auto-save-visited-mode t
      auto-revert-mode t)
#+end_src
* Editor
** Fonts
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:
+ =doom-font=
+ =doom-variable-pitch-font=
+ =doom-big-font= :: used for =doom-big-font-mode=; use this for presentations or streaming.
They all accept either a font-spec, font string ("Input Mono-12"), or xlfd font string.
You generally only need these two:

#+BEGIN_SRC elisp
(setq doom-font (font-spec :family "Cascadia Mono PL" :size 13 :weight 'regular)
      doom-big-font (font-spec :family "Cascadia Mono PL" :size 20 :weight 'bold))
#+END_SRC

** Line numbers
This determines the style of line numbers in effect. If set to =nil=, line
numbers are disabled. For relative line numbers, set this to =relative=.
#+BEGIN_SRC elisp
(setq display-line-numbers-type t)
#+END_SRC

** Linewrapping
#+begin_src elisp
(setq global-visual-line-mode t)
#+end_src
If you want ~auto-fill~ mode on in all major modes, do this:
#+begin_src elisp :tangle no
(setq-default auto-fill-function 'do-auto-fill
              fill-column 80)
#+end_src
** [[https://github.com/abo-abo/hydra][Hydra]]
*** Quick UI adjustments for screen sharing from Sullivan: [[https://eamonnsullivan.co.uk/posts-output/2020-04-25-remote-first-emacs/][Pair programming and Emacs]]
I've been getting the message "Eager macro-expansion failure: (void-variable hydra-ivy/params)".
Seems related to [[https://github.com/abo-abo/hydra/issues/9][this issue]].

#+begin_src elisp
(global-set-key
    (kbd "C-z")
    (defhydra hydra-global-menu (:color red :hint nil)
   "
^Display^        ^Buffers^                    ^Actions^
^^^^^^^^^-----------------------------------------------------
_g_: zoom in     _d_: close all buffers       _u_: update all packages
_s_: zoom out    _o_: open buffer on desktop  _l_: display line numbers

_q_: quit this menu                         _r_: restart emacs
"
   ("g" text-scale-increase)
   ("s" text-scale-decrease)
   ("d" kill-all-buffers)
   ("l" global-display-line-numbers-mode)
   ("r" stop-and-restart-emacs)
   ("u" eds-straight-pull-or-prune)
   ("o" eds/open-buffer-on-desktop)
   ("q" nil)))
#+end_src

** Other
#+begin_src elisp
(setq auto-save-default nil
      make-backup-files nil)
(delete-selection-mode 1)                       ; Replace selection when inserting text
(global-subword-mode 1)                         ; Iterate through CamelCase words
#+end_src

* Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set =doom-theme= or manually load a theme with the
=load-theme= function.

See this [[https://github.com/hlissner/emacs-doom-themes/issues/216][issue]] for instructions on overriding particular colors. See [[https://github.com/hlissner/emacs-doom-themes/blob/89a22c954e4989e3bc0abe4dd9cf8b7e95826140/doom-themes.el][doom-themes.el]] for the definition of =doom-lighten=. The color ~fg-1~ is defined [[https://github.com/hlissner/emacs-doom-themes/pull/447/commits/c44bfee1d9e2e1732ca5b36fbc13e0149f846a6a][here]]. See [[https://github.com/tkf/org-mode/blob/master/lisp/org-faces.el][org-faces.el]] for the list of faces you can set in Org mode.

#+begin_src elisp
(load-theme 'doom-zenburn t)
(custom-theme-set-faces! 'doom-zenburn
  `(org-document-info-keyword :foreground ,(doom-lighten 'fg-1 0.2))
  `(org-done :foreground ,(doom-lighten 'fg-1 0.05))
  `(org-ellipsis :foreground ,(doom-lighten 'fg-1 0.2)))
#+end_src

* Org mode
** Set directories
If you use =org= and don't want your org files in the default location below, change =org-directory=. It must be set before org loads!
#+BEGIN_SRC elisp
(setq org-dir (concat (getenv "HOME") "/Dropbox/org/")
      crewsbib-dir (concat (getenv "HOME") "/Dropbox/crewsbib/")
      crewsbib (concat crewsbib-dir "crewsbib.bib")
      org-directory org-dir
      deft-directory (concat org-dir "roam/")
      org-roam-directory (concat org-dir "roam/")
      org-roam-dailies-directory (concat org-dir "roam/journal/")
      reftex-default-bibliography (list crewsbib))
#+END_SRC

** Global keybindings
#+begin_src elisp
(after! org
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key (kbd "C-c a") 'org-agenda)
  (global-set-key (kbd "C-c c") 'org-capture))
#+end_src

** Formatting
#+begin_src elisp
(after! org
  (setq org-ellipsis " ▼" ;; …, ↴, ⬎
        org-hide-leading-stars t
        org-startup-indented t
        org-startup-folded t
        org-fontify-done-headline nil))
#+end_src

** Logging
#+begin_src elisp
(after! org
  (setq org-log-done t
        org-log-into-drawer t
        org-clock-into-drawer t))
#+end_src

** Set todo keywords
- ideally each would be only four letters (hence KILL for CANCELLED)
- reading TODO sequence implements the three stages of reading from Adler & Van Doren
#+begin_src elisp
(after! org
  (setq org-todo-keywords
  '((sequence "TODO(t)" "NEXT(n)" "ONGO(o!)" "WAIT(w@/!)" "|" "DONE(d)" "KILL(k)")
    (sequence "INSPECT(i)" "UNDERSTAND(u!)" "EVAL(e!)" "|" "READ(r)" "KILL(k!)"))))
#+end_src

** [[https://github.com/alphapapa/org-super-agenda][Org-super-agenda]]
This package lets you "supercharge" your Org daily/weekly agenda. The idea is to group items into sections, rather than having them all in one big list.

This package filters the results from =org-agenda-finalize-entries=, which runs just before items are inserted into agenda views. The filtered groups are then inserted into the agenda buffer, and any remaining items are inserted at the end. Empty groups are not displayed.

The end result is your standard daily/weekly agenda, but arranged into groups defined by you. You might put items with certain tags in one group, habits in another group, items with certain todo keywords in another, and items with certain priorities in another. The possibilities are only limited by the grouping functions.

The primary use of this package is for the daily/weekly agenda, made by the org-agenda-list command, but it also works for other agenda views, like org-tags-view, org-todo-list, org-search-view, etc. See the official set of examples [[https://github.com/alphapapa/org-super-agenda/blob/master/examples.org][here]].

/Note again/: =org-super-agenda= does *not* collect items! It only groups items that are collected by =org-agenda= or [[https://github.com/alphapapa/org-ql][=org-ql=]], which provides an easier way to write queries to generate agenda-like views. So if your Agenda command or =org-ql= query does not collect certain items, they will not be displayed, regardless of what =org-super-agenda= groups you configure.

The following custom agenda view combines two =org-super-agenda= filters in a [[https://orgmode.org/manual/Block-agenda.html][block agenda]].

*** TODO [[https://orgmode.org/manual/Tracking-your-habits.html#Tracking-your-habits][habits]]
- daily initiation
- GitHub commit
- nightly shut down
- chastity
- weekly review
- quarterly review
- annual review
*** TODO what custom views do I want?
**** proposed groups
- the schedule for today (DOs and DUEs + clocked time)
- habits
- SYSTEM (reading, gardening, maintenance, etc.)
- research projects (publication pipeline)
  + NEXT or ONGO
  + any reading headlines (INSPECT, UNDERSTAND, EVAL)
- teaching + service: NEXT or ONGO
- upcoming seminars?
- home: NEXT or ONGO
- all other NEXT or ONGO
**** potential add-ons
- will tags or categories play a role?
  + categories are (by default) just the filename in which the TODO is stored
- effort estimates?
- show clocked tasks in the clock-view?
*** code
#+begin_src elisp
(use-package! org-super-agenda
  :after org-agenda
  :init
  (setq org-agenda-restore-windows-after-quit t
        org-agenda-start-with-log-mode t ;; show clocked and closed tasks in agenda
        org-agenda-span 'week
        org-agenda-start-on-weekday 1 ;; 0 for Sunday, 1 for Monday
        org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done t
        org-agenda-include-deadlines t
        org-agenda-breadcrumbs-separator " ❱ "
        org-agenda-block-separator nil
        org-agenda-compact-blocks t)
  (setq org-agenda-custom-commands
        '(("c" "Super view"
           ((agenda "" ((org-agenda-span 'day)
                        (org-agenda-start-day nil)
                        (org-agenda-overriding-header "")
                        (org-super-agenda-groups
                         '((:name "Lagging"
                            :scheduled past
                            :deadline past)
                           (:name "Today"
                            :time-grid t
                            :log t ;; clocked and closed
                            :date today ;; meetings
                            :scheduled today ;; DOs vs DUEs (deadlines)
                            :deadline today)
                           (:name "Upcoming"
                            :scheduled future
                            :deadline future)))))
            (todo "NEXT|ONGO" ((org-agenda-overriding-header "")
                         (org-super-agenda-groups
                          '((:name "Habits"
                             :habit t)
                            (:name "Research pipeline"
                             :file-path "[^a-z0-9]p-[a-z0-9]*\\.org")
                            (:name "Teaching + Service"
                             :file-path ("econ27000-intl\\.org" "bus33503-mfge\\.org" "service-econ\\.org"))
                            (:name "SysAdmin"
                             :file-path ("foreman\\.org" "system.*\\.org"))
                            (:name "Home"
                             :file-path "home\\.org")))))))))
  :config
  (org-super-agenda-mode))
#+end_src
** [[https://github.com/fuxialexander/org-pdftools][Org-pdftools]] + [[https://github.com/weirdNox/org-noter][Org-noter]]
Both ~org-pdftools~ and ~org-noter!~ have elsewhere been loaded in this Doom config:
~org-pdftools~ through the ~:tools pdf~ option and ~org-noter~ through the ~org + noter~ flag in ~init.el~.
The code below (from ~org-pdftools/README.org~) just ensures that the two packages are tied together properly.

#+begin_src elisp
(use-package! org-noter-pdftools
  :after org-noter
  :config
  (with-eval-after-load 'pdf-annot
    (add-hook 'pdf-annot-activate-handler-functions #'org-noter-pdftools-jump-to-note)))
#+end_src

** [[https://github.com/jkitchin/org-ref][Org-ref]]
Note that the ivy-backend ~org-ref~ is [[https://github.com/jkitchin/org-ref/issues/793][not actually]] ~ivy-bibtex~! If you want to use the Helm-bibtex package with ~org-ref~, you need to actually use ~helm-bibtex~, which means that you need to use ~helm~ for search in your Doom ~init.el~. If you stick with ~ivy~, as I'm doing here, see [[https://github.com/jkitchin/org-ref/issues/717][this snippet]] to make a nicer display.

#+begin_src elisp :tangle no
(use-package! org-ref
    :after org
    :init
    (setq org-ref-completion-library 'org-ref-ivy-cite)
    :config
    (setq org-ref-default-bibliography (list crewsbib)
          org-ref-default-citation-link "citet"
          org-ref-notes-directory (concat org-roam-directory "refs/")
          org-ref-notes-function 'orb-edit-notes
          org-ref-pdf-directory (concat crewsbib-dir "pdf/")
          org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex))
#+end_src

#+begin_src elisp
(use-package! ivy-bibtex
  :when (featurep! :completion ivy)
  :config
  (add-to-list 'ivy-re-builders-alist '(ivy-bibtex . ivy--regex-plus))
  ;;(ivy-set-display-transformer 'org-ref-ivy-insert-cite-link 'ivy-bibtex-display-transformer)
  )
#+end_src

** [[https://github.com/tmalsburg/helm-bibtex][Helm-bibtex]]

#+begin_src elisp
(use-package! bibtex-completion
  :defer t
  :config
  (setq bibtex-completion-bibliography crewsbib
        bibtex-completion-library-path (concat crewsbib-dir "pdf/")
        bibtex-completion-pdf-field "file" ;; pulls PDF path from "File" field of JabRef
        bibtex-completion-find-additional-pdfs t ;; will match all <citekey>-appendix.pdf
        bibtex-completion-notes-path (concat org-roam-directory "refs") ;; one note file per reference
        bibtex-completion-notes-template-multiple-files
        (concat
         "#+TITLE: ${title}\n"
         "#+ROAM_KEY: cite:${=key=}\n"
         "#+ROAM_TAGS: ${keywords}\n"
         "* INSPECT RAP\n"
         ":PROPERTIES:\n"
         ":Custom_ID: ${=key=}\n"
         ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
         ":AUTHOR: ${authors}\n"
         ":JOURNAL: ${journaltitle}\n"
         ":YEAR: ${year}\n"
         ":DOI: ${doi}\n"
         ":END:\n\n")
        bibtex-completion-additional-search-fields '(keywords journal booktitle)
        bibtex-completion-display-formats
        '((article       . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*} ${journal:20}")
          (book          . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*}")
          (inbook        . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*} Chapter ${chapter:30}")
          (incollection  . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*} ${booktitle:30}")
          (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*} ${booktitle:30}")
          (t             . "${=has-pdf=:1}${=has-note=:1} ${=type=:4} ${year:4} ${author:36} ${title:*}"))
        bibtex-completion-pdf-symbol "▛"
        bibtex-completion-notes-symbol "§"
        bibtex-completion-format-citation-functions
            '((org-mode      . bibtex-completion-format-citation-org-title-link-to-PDF)
              (latex-mode    . bibtex-completion-format-citation-cite)
              (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
              (default       . bibtex-completion-format-citation-default))
        ))
#+end_src

** [[https://github.com/jrblevin/deft][Deft]]
Used to search through my org-roam files (daily entries + permanent notes).
Keep all of Doom's default settings, less evil keybindings.
File names are automatically set in ~kebab-case~ using the note's title.
~deft-recursive~ is turned on to search subdirectories.
The default note extension is ~.org~.
Use =C-c C-q= to quit!

#+begin_src elisp
(use-package! deft
  :after org
  :bind
  ("C-c n s" . deft)
  :init
  (setq deft-file-naming-rules
      '((noslash . "-")
        (nospace . "-")
        (case-fn . downcase)))
  :custom
  (deft-recursive t)
  (deft-use-filename-as-title nil)
  (deft-use-filter-string-for-filename t)
  (deft-extensions '("tex" "org"))
  (deft-default-extension "org"))
#+end_src

** [[https://github.com/org-roam/org-roam][Org-roam]]
Org-roam is a plain-text knowledge management system.
See the manual [[https://www.orgroam.com/manual.html][here]].
*** Daily journal
Org-roam has a [[https://youtu.be/1q9x2aZCJJ4][dailies page]] that uses [[https://github.com/bastibe/org-journal][org-journal]] (or, at least, some of the code) as a backend.
Org-journal on its own [[https://org-roam.discourse.group/t/org-journal-vs-org-roam-dailies/384][handles TODOs better]], but I don't want any TODOs in my journal anyways.
The issues [[https://github.com/bastibe/org-journal/pull/278][here]] and [[https://github.com/org-roam/org-roam/pull/978][here]] suggest a permanent divorce of Org-roam from Org-journal as of late July 2020.
(Finalized 10 Nov 2020.)
*** code
#+begin_src elisp
(use-package! org-roam
  :after org
  :bind (("C-c n d" . org-roam-today)
         :map org-mode-map
         (("C-c n l" . org-roam) ;; call this to show backlinks in side-buffer
          ("C-c n u" . org-roam-update-buffer)
          ("C-c n i" . org-roam-insert)
          ("C-c n c" . org-roam-capture)
          ("C-c n g" . org-roam-graph)
          ("C-c n r" . org-roam-random-note)))
  :config
  ;;(org-roam-tag-sources '(prop last-directory))
  (setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         #'org-roam-capture--get-point
         "* %?"
         :file-name "journal/%<%Y-%m-%d>"
         :head "#+title: %<%d-%B-%Y>\n\n"))))
#+end_src

*** [[https://github.com/org-roam/org-roam-bibtex][Org-roam-bibtex]]

#+begin_src elisp
(use-package! org-roam-bibtex
  :after (org-roam)
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :bind (:map org-roam-bibtex-mode-map
         (("C-c n f" . orb-find-non-ref-file))
         :map org-mode-map
         (("C-c n t" . orb-insert-non-ref)
          ("C-c n a" . orb-note-actions)))
  :config
  ;;(orb-autokey-format "%A[5]%y")
  ;;(​orb-note-actions-interface 'ivy)
  (orb-templates
   `(("r" "ref" plain
      (function org-roam-capture--get-point)
      ""
      :file-name "refs/${citekey}"
      :head ,(s-join "\n"
                     (list
                      (concat "#+title: "
                              orb-title-format)
                      "#+roam_key: ${ref}"
                      "#+created: %U"
                      "#+last_modified: %U\n\n"))
      :unnarrowed t)
     ("p" "ref + physical" plain
      (function org-roam-capture--get-point)
      ""
      :file-name "refs/${citekey}"
      :head ,(s-join "\n"
                     (list
                      (concat "#+title: "
                              orb-title-format)
                      "#+roam_key: ${ref}"
                      ""
                      "* RAP+M :physical:")))
     ("n" "ref + noter" plain
      (function org-roam-capture--get-point)
      ""
      :file-name "refs/${citekey}"
      :head ,(s-join "\n"
                     (list
                      (concat "#+title: "
                              orb-title-format)
                      "#+roam_key: ${ref}"
                      ""
                      "* RAP+M :noter:"
                      ":PROPERTIES:"
                      ":NOTER_DOCUMENT: %(orb-process-file-field \"${citekey}\")"
                      ":NOTER_PAGE:"
                      ":END:"))))))
#+end_src

* LaTeX
** PDF viewer
#+begin_src elisp :tangle no
(after! org
  (setq +latex-viewers '(zathura)))
#+end_src
** Recipe
From the ~org-ref~ documentation: "If you plan to build PDF files via LaTeX you need to make sure that org-latex-pdf-process is set to process the bibliography (using bibtex or biblatex). Here is one example of how to do that"

#+begin_src elisp
(after! org
  (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f")))
#+end_src
