# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

# Always show username?
[username]
show_always = false

# Only show hostname when connected to an SSH session
[hostname]
ssh_only = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Truncate directory from the right
[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "…/"

# Keep defaults for all Git modules

# Turn off language modules
[python]
disabled = true

[julia]
disabled = true